services:
  - type: web
    name: my-backend
    env: node
    rootDir: .
    buildCommand: cd .. && npm install && npm run server
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5100
